CXX=         g++
CXXFLAGS=    -g -Wall -Werror -Wpedantic -std=c++20

default: clean all

task:

.PHONY: all
all: task
	cat input.txt | ./task

.PHONY: clean
clean:
	rm -rf a.out *.o task output.txt

.PHONY: Makefile


